Algoritmo "graos"
// Unidade Curricular  :  [Lógica de Programação] 
// Professor   : Luiz Cesar Gawlik - LC 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/03/2017
Var
// Seção de Declarações das variáveis 
   f, c:real

Inicio
   escreva("quantos graos em celcios")
   leia(c)
   f:=((9*c)+160)/5
   escreval("a temperatura em fahreiheit e",f)
Fimalgoritmo