Algoritmo "rendimento"
// Unidade Curricular  :  [Lógica de Programação] 
// Professor   : Luiz Cesar Gawlik - LC 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/03/2017
Var
// Seção de Declarações das variáveis 
    deposito, rendimento:real
Inicio
    escreval("valor depositado")
    leia(deposito)
    rendimento:=(deposito*1.7)
    escreva("o valor apos um mes sera de",rendimento)
Fimalgoritmo