Algoritmo "semnome"
// Unidade Curricular  :  [Lógica de Programação] 
// Professor   : Luiz Cesar Gawlik - LC 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/03/2017
Var
// Seção de Declarações das variáveis 
// np sao o numero de parcelas
    valor, np, vt:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreval("")

Fimalgoritmo